version: '3.7'

services:
  airflow-pg:
    container_name: airflow-pg
    image: library/postgres:13.1-alpine
    volumes:
      - airflow-pg-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=$PG_DB
      - POSTGRES_USER=$PG_USER
      - POSTGRES_PASSWORD=$PG_PASS
    networks:
      - airflow-net
    ports:
      - $PG_PORT:5432

  airflow-redis:
    container_name: airflow-redis
    image: redis:6.2.1-alpine3.13
    command: redis-server --requirepass ${REDIS_PASS} --loglevel notice
    volumes:
      - airflow-redis-data:/data
    environment:
      - REDIS_PASS
    networks:
      - airflow-net
    ports:
      - $REDIS_PORT:6379

volumes:
  airflow-pg-data:
    name: airflow-pg-data
  airflow-redis-data:
    name: airflow-redis-data

networks:
  airflow-net:
    name: airflow-net
